FUENTES = [
    {"nombre": "BioBio Chile", "url": "https://www.biobiochile.cl/feed/", "categoria": "nacional"},
    {"nombre": "Emol", "url": "https://www.emol.com/rss/rss.asp", "categoria": "nacional"},
    {"nombre": "La Tercera", "url": "https://www.latercera.com/feed/", "categoria": "nacional"},
    {"nombre": "Cooperativa", "url": "https://www.cooperativa.cl/prontus/feed/rss/", "categoria": "nacional"},
    {"nombre": "T13", "url": "https://www.t13.cl/rss/nacional.xml", "categoria": "nacional"},
    {"nombre": "ADN Radio", "url": "https://www.adnradio.cl/feed/", "categoria": "nacional"},
    {"nombre": "El Mostrador", "url": "https://www.elmostrador.cl/feed/", "categoria": "nacional"},
    {"nombre": "Defensa.cl", "url": "https://www.defensa.cl/feed/", "categoria": "defensa"},
    {"nombre": "Armada Chile", "url": "https://www.armada.cl/rss/noticias", "categoria": "defensa"},
    {"nombre": "Senado.cl", "url": "https://www.senado.cl/feed/noticias", "categoria": "legislativo"},
    {"nombre": "Camara Diputados", "url": "https://www.camara.cl/feed/noticias.aspx", "categoria": "legislativo"},
    {"nombre": "SENAPRED", "url": "https://www.senapred.cl/feed/", "categoria": "emergencia"},
    {"nombre": "Cochilco", "url": "https://www.cochilco.cl/feed/", "categoria": "economia"},
    {"nombre": "Codelco", "url": "https://www.codelco.com/prensa/noticias/rss", "categoria": "economia"},
    {"nombre": "Diario Financiero", "url": "https://www.df.cl/feed/", "categoria": "economia"},
    {"nombre": "Soy Arica", "url": "https://www.soychile.cl/arica/rss/", "categoria": "norte"},
    {"nombre": "Soy Iquique", "url": "https://www.soychile.cl/iquique/rss/", "categoria": "norte"},
    {"nombre": "Soy Antofagasta", "url": "https://www.soychile.cl/antofagasta/rss/", "categoria": "norte"},
    {"nombre": "El Mercurio Antofagasta", "url": "https://www.mercurioantofagasta.cl/rss/", "categoria": "norte"},
    {"nombre": "PDI Chile", "url": "https://www.pdichile.cl/feed/", "categoria": "seguridad"},
    {"nombre": "Carabineros", "url": "https://www.carabineros.cl/feed/", "categoria": "seguridad"},
    {"nombre": "CSIRT Chile", "url": "https://www.csirt.gob.cl/feed/", "categoria": "infosec"},
    {"nombre": "MOP Chile", "url": "https://www.mop.cl/feed/", "categoria": "infra"},
    {"nombre": "Aduanas Chile", "url": "https://www.aduana.cl/feed/", "categoria": "frontera"},
    {"nombre": "Infobae Peru", "url": "https://www.infobae.com/peru/feed/", "categoria": "exterior"},
]
