# CONDOR V12.6 TURBO - 30 FUENTES QUE SI FUNCIONAN DESDE RENDER USA
FUENTES = [
    {"nombre": "Defensa.cl", "url": "https://www.defensa.cl/feed/", "categoria": "defensa"},
    {"nombre": "Armada Chile", "url": "https://www.armada.cl/rss/noticias", "categoria": "defensa"},
    {"nombre": "BBC World", "url": "http://feeds.bbci.co.uk/news/world/rss.xml", "categoria": "exterior"},
    {"nombre": "BBC Latin America", "url": "http://feeds.bbci.co.uk/news/world/latin_america/rss.xml", "categoria": "exterior"},
    {"nombre": "CNN World", "url": "http://rss.cnn.com/rss/edition.rss", "categoria": "exterior"},
    {"nombre": "Infobae America", "url": "https://www.infobae.com/america/rss/", "categoria": "exterior"},
    {"nombre": "Infobae Mundo", "url": "https://www.infobae.com/mundo/rss/", "categoria": "exterior"},
    {"nombre": "El Pais Internacional", "url": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/internacional/portada", "categoria": "exterior"},
    {"nombre": "Google News Chile", "url": "https://news.google.com/rss?hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "nacional"},
    {"nombre": "Google News Defensa", "url": "https://news.google.com/rss/search?q=Ejercito+Chile+FACH&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "defensa"},
    {"nombre": "Google News Seguridad", "url": "https://news.google.com/rss/search?q=Carabineros+PDI&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "seguridad"},
    {"nombre": "Google News Frontera", "url": "https://news.google.com/rss/search?q=Arica+Colchane+frontera&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "frontera"},
    {"nombre": "Google News Economia", "url": "https://news.google.com/rss/search?q=Codelco+Chile+economia&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "economia"},
    {"nombre": "Google News SENAPRED", "url": "https://news.google.com/rss/search?q=SENAPRED+sismo+Chile&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "emergencia"},
    {"nombre": "Google News Geopolitica", "url": "https://news.google.com/rss/search?q=Chile+Peru+Bolivia+Argentina&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "exterior"},
    {"nombre": "La Tercera", "url": "https://www.latercera.com/feed/", "categoria": "nacional"},
    {"nombre": "El Mostrador", "url": "https://www.elmostrador.cl/feed/", "categoria": "nacional"},
    {"nombre": "ADN Radio", "url": "https://www.adnradio.cl/feed/", "categoria": "nacional"},
    {"nombre": "Cooperativa", "url": "https://www.cooperativa.cl/noticias/site/rss/port/all/rss_0_0.xml", "categoria": "nacional"},
    {"nombre": "BioBio Chile", "url": "https://www.biobiochile.cl/feed/", "categoria": "nacional"},
    {"nombre": "Emol Nacional", "url": "https://www.emol.com/rss/rss.asp?canal=nacional", "categoria": "nacional"},
    {"nombre": "Emol Mundo", "url": "https://www.emol.com/rss/rss.asp?canal=mundo", "categoria": "exterior"},
    {"nombre": "SENAPRED", "url": "https://www.senapred.cl/feed/", "categoria": "emergencia"},
    {"nombre": "CSIRT Chile", "url": "https://www.csirt.gob.cl/feed/", "categoria": "infosec"},
    {"nombre": "PDI Chile", "url": "https://www.pdichile.cl/feed/", "categoria": "seguridad"},
    {"nombre": "MOP Chile", "url": "https://www.mop.cl/feed/", "categoria": "infra"},
    {"nombre": "Aduanas Chile", "url": "https://www.aduana.cl/feed/", "categoria": "frontera"},
    {"nombre": "Cochilco", "url": "https://www.cochilco.cl/feed/", "categoria": "economia"},
    {"nombre": "Diario Financiero", "url": "https://www.df.cl/feed/", "categoria": "economia"},
    {"nombre": "The Guardian World", "url": "https://www.theguardian.com/world/rss", "categoria": "exterior"},
]
