# CONDOR V14 ULTRA - 35 FUENTES ANTI-BLOQUEO USA
# Estrategia: 28 Google News (100% pasan desde Render USA) + 7 internacionales directas que pasan
FUENTES = [
    # INTERNACIONALES QUE SI PASAN DESDE USA
    {"nombre": "BBC World", "url": "http://feeds.bbci.co.uk/news/world/rss.xml", "categoria": "internacional"},
    {"nombre": "BBC LatAm", "url": "http://feeds.bbci.co.uk/news/world/latin_america/rss.xml", "categoria": "internacional"},
    {"nombre": "The Guardian World", "url": "https://www.theguardian.com/world/rss", "categoria": "internacional"},
    {"nombre": "CNN World", "url": "http://rss.cnn.com/rss/edition.rss", "categoria": "internacional"},
    {"nombre": "El Pais Int", "url": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/internacional/portada", "categoria": "internacional"},
    {"nombre": "Defensa.cl", "url": "https://www.defensa.cl/feed/", "categoria": "defensa"},
    {"nombre": "Infobae Mundo", "url": "https://www.infobae.com/arc/outboundfeeds/rss/", "categoria": "internacional"},

    # GOOGLE NEWS CHILE - TODOS PASAN DESDE RENDER USA (28 fuentes)
    {"nombre": "GNews Chile General", "url": "https://news.google.com/rss?hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "prensa"},
    {"nombre": "GNews Defensa FACH", "url": "https://news.google.com/rss/search?q=FACH+Chile+Fuerza+Aerea&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "defensa"},
    {"nombre": "GNews Ejercito", "url": "https://news.google.com/rss/search?q=Ejercito+de+Chile&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "defensa"},
    {"nombre": "GNews Armada", "url": "https://news.google.com/rss/search?q=Armada+de+Chile&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "defensa"},
    {"nombre": "GNews Carabineros", "url": "https://news.google.com/rss/search?q=Carabineros+de+Chile&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "riesgo"},
    {"nombre": "GNews PDI", "url": "https://news.google.com/rss/search?q=PDI+Chile+Policia+Investigaciones&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "riesgo"},
    {"nombre": "GNews Frontera Norte", "url": "https://news.google.com/rss/search?q=Colchane+Arica+frontera+norte&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "frontera"},
    {"nombre": "GNews Frontera Libertadores", "url": "https://news.google.com/rss/search?q=Paso+Los+Libertadores+frontera&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "frontera"},
    {"nombre": "GNews Frontera Chacalluta", "url": "https://news.google.com/rss/search?q=Chacalluta+Arica+frontera+Peru&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "frontera"},
    {"nombre": "GNews Migracion", "url": "https://news.google.com/rss/search?q=migracion+irregular+Chile+Colchane&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "frontera"},
    {"nombre": "GNews Narcotrafico", "url": "https://news.google.com/rss/search?q=narcotrafico+frontera+Chile&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "riesgo"},
    {"nombre": "GNews Codelco Cobre", "url": "https://news.google.com/rss/search?q=Codelco+cobre+Chile&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "economico"},
    {"nombre": "GNews Litio", "url": "https://news.google.com/rss/search?q=litio+Chile+SQM&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "economico"},
    {"nombre": "GNews Economia", "url": "https://news.google.com/rss/search?q=economia+Chile+imacec&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "economico"},
    {"nombre": "GNews Politica", "url": "https://news.google.com/rss/search?q=La+Moneda+gobierno+Chile&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "prensa"},
    {"nombre": "GNews SENAPRED", "url": "https://news.google.com/rss/search?q=SENAPRED+sismo+Chile&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "riesgo"},
    {"nombre": "GNews Sismo", "url": "https://news.google.com/rss/search?q=sismo+temblor+Chile+hoy&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "riesgo"},
    {"nombre": "GNews Ciberseguridad", "url": "https://news.google.com/rss/search?q=ciberseguridad+CSIRT+Chile&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "riesgo"},
    {"nombre": "GNews Aduanas", "url": "https://news.google.com/rss/search?q=Aduanas+Chile+contrabando&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "frontera"},
    {"nombre": "GNews MOP", "url": "https://news.google.com/rss/search?q=MOP+Chile+obras+publicas&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "economico"},
    {"nombre": "GNews Interior", "url": "https://news.google.com/rss/search?q=Ministerio+Interior+Chile+seguridad&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "prensa"},
    {"nombre": "GNews Cancilleria", "url": "https://news.google.com/rss/search?q=Cancilleria+Chile+relaciones+exteriores&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "internacional"},
    {"nombre": "GNews Peru", "url": "https://news.google.com/rss/search?q=Chile+Peru+frontera+relaciones&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "internacional"},
    {"nombre": "GNews Bolivia", "url": "https://news.google.com/rss/search?q=Chile+Bolivia+frontera+Colchane&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "internacional"},
    {"nombre": "GNews Argentina", "url": "https://news.google.com/rss/search?q=Chile+Argentina+Los+Libertadores&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "internacional"},
    {"nombre": "GNews Valparaiso", "url": "https://news.google.com/rss/search?q=Valparaiso+puerto+Chile&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "economico"},
    {"nombre": "GNews Arica", "url": "https://news.google.com/rss/search?q=Arica+Parinacota+frontera&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "frontera"},
    {"nombre": "GNews Iquique", "url": "https://news.google.com/rss/search?q=Iquique+Tamarugal+frontera&hl=es-419&gl=CL&ceid=CL:es-419", "categoria": "frontera"},
]
